//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetShield_Protector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetShield_Protector.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///using System.Security.Cryptography;
        ///using System.Management;
        ///using System.Reflection;
        ///using System.Text;
        ///using System.Runtime.InteropServices;
        ///using System.Diagnostics;
        ///
        ///HWIDPacker
        ///{
        ///    static class Program
        ///    {
        ///        static string ProgramToDecrypt = &quot;DecME&quot;;
        ///        static string IV = &quot;THISISIV&quot;;
        ///
        ///        [DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HWIDPacker {
            get {
                return ResourceManager.GetString("HWIDPacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///LicensePacker
        ///{
        ///    static class Program
        ///    {
        ///        static string ProgramToDecrypt = &quot;DecME&quot;;
        ///        static string IV = &quot;THISISIV&quot;;
        ///
        ///        [DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        pri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicensePacker {
            get {
                return ResourceManager.GetString("LicensePacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Runtime.InteropServices;
        ///using System.Diagnostics;
        ///using System.Reflection;
        ///
        ///namespace PackStub
        ///{
        ///    static class Program
        ///    {
        ///        [DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        private static extern bool IsDebuggerPresent();
        ///
        ///        static string fMJUcafeoygb = &quot;DecME&quot;;
        ///        sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PackStub {
            get {
                return ResourceManager.GetString("PackStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Management;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///
        ///USBPacker
        ///{
        ///    internal static class Program
        ///    {
        ///        private static string ProgramToDecrypt = &quot;DecME&quot;;
        ///        private static string IV = &quot;THISISIV&quot;;
        ///
        ///        [DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        private static extern bool IsDebuggerPrese [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USBPacker {
            get {
                return ResourceManager.GetString("USBPacker", resourceCulture);
            }
        }
    }
}
